language: ruby

rvm:
  - 2.0.0

cache: bundler

env:
  global:
    - DEPLOY_BRANCH=gh-pages-test
    - JEKYLL_ENV=production

script: scripts/build.sh

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: feature/travis