# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: API Handyman
description: '{"input" : "learn", "output" : "share"}'

url: "http://apihandyman.io" # the base hostname & protocol for your site
twitter_username: apihandyman
github_username:  arno-di-loreto
linkedin_username: arnaudlauret
default_thumbnail: /images/commons/thumbnail.png
google_analytics: UA-58046291-1
disqus:
  shortname: apihandyman

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  

gems:
  - jekyll-feed
  - jekyll-twitter-plugin

exclude:
  - Gemfile
  - Gemfile.lock